// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Stablishing_Category_News_Relation_Cateory_Side : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stablishing_Category_News_Relation_Cateory_Side));
        
        string IMigrationMetadata.Id
        {
            get { return "202307230818229_Stablishing_Category_News_Relation_Cateory_Side"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
