// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Feeding_News_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feeding_News_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "202307230826518_Feeding_News_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
